### ISSUE TITLE
A couple of things

### ISSUE THREAD

**Issue by ghost** [its5Q/ducominer#1]
Hello! Thanks for making this project, it seems to be really interesting.

I have a couple of tips for you:
- For Windows you also need to ship two SSL dlls on 64bit, namely ssleay64.dll and libeay64.dll, you can get those from https://nim-lang.org/download/dlls.zip
- Specifying -d:danger in https://github.com/its5Q/ducominer/blob/main/ducominer.nim.cfg does not actually apply it (because user config is evaluated after the global one, so -d:danger does not actually change anything)

You need to pass -d:release and/or -d:danger explicitly in the command line (or in Nimble tasks) for it to apply.

**Comment by ghost** [comment]
I also have some minor code improvements which I will probably do in a PR :)

**Comment by ghost** [comment]
Also, do you happen to know why with ducominer my DuinoCoin wallet balance doesn't seem to change (it changes with the web miner though)?

**Comment by ghost** [comment]
Hmm, it seems to work if I authenticate with duino coin's protocol, but just "JOB,username" doesn't seem to add balance to my own account :thinking:

**Comment by its5Q** [comment]
> Hmm, it seems to work if I authenticate with duino coin's protocol, but just "JOB,username" doesn't seem to add balance to my own account 🤔

Hmm, strange, it works perfectly fine with JOB,username for me.

**Comment by its5Q** [comment]
Also, thanks for the tips, I will make a release with the libssl included.

**Comment by its5Q** [comment]
> Hmm, it seems to work if I authenticate with duino coin's protocol, but just "JOB,username" doesn't seem to add balance to my own account 🤔

I've fixed the issue, it was in my donation system. Turns out that the server accepts all shares under the first username that was sent to the server. And because it determines when the share submits as my username, it uses modulo, so the first share was always sent under my username, and so would the rest of the shares.
